name: Build APK

on:
  push:
  workflow_dispatch:
    inputs:
      XRAY_CORE_VERSION:
        description: 'Xray core version or commit hash'
        required: false


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Setup Golang
      uses: actions/setup-go@v5
      with:
        go-version: '1.22.2'

    - name: Install gomobile
      run: |
        go install golang.org/x/mobile/cmd/gomobile@latest
        echo "$(go env GOPATH)/bin" >> $GITHUB_PATH


    - name: Setup Android environment
      uses: android-actions/setup-android@v3


- name: Build dependencies
  run: |
    mkdir -p ${{ github.workspace }}/build
    cd ${{ github.workspace }}/build
    git clone --depth=1 -b main https://github.com/2dust/AndroidLibXrayLite.git
    cd AndroidLibXrayLite
    go get github.com/xtls/xray-core@${{ github.event.inputs.XRAY_CORE_VERSION }} || true
    go mod tidy -v
    go mod download
    gomobile init
    gomobile bind -v -androidapi 21 -ldflags='-s -w' ./
    cp *.aar ${{ github.workspace }}/YiLink/app/libs/

    - name: Build APK
      run: |
        cd ${{ github.workspace }}/YiLink
        chmod 755 gradlew
        ./gradlew clean
        ./gradlew assembleRelease
    
    - name: Upload Aritfact
      uses: actions/upload-artifact@v4
      with:
        name: release Unsigned APK (universal) 
        path: ${{ github.workspace }}/YiLink/app/build/outputs/apk/release/
      
    - name: Upload Aritfact (universal)
      uses: actions/upload-artifact@v4
      with:
        name: release Unsigned APK (universal) 
        path: ${{ github.workspace }}/YiLink/app/build/outputs/apk/release/*universal.apk
      
    - name: Upload Aritfact (arm64-v8a)
      uses: actions/upload-artifact@v4
      with:
        name: release Unsigned APK (arm64-v8a)
        path: ${{ github.workspace }}/YiLink/app/build/outputs/apk/release/*arm64-v8a.apk
      
    - name: Upload Aritfact (armeabi-v7a)
      uses: actions/upload-artifact@v4
      with:
        name: release Unsigned APK (armeabi-v7a)
        path: ${{ github.workspace }}/YiLink/app/build/outputs/apk/release/*armeabi-v7a.apk
      
    - name: Upload Aritfact (x86_64)
      uses: actions/upload-artifact@v4
      with:
        name: release Unsigned APK (x86_64)
        path: ${{ github.workspace }}/YiLink/app/build/outputs/apk/release/*x86_64.apk
          